[project]
name = "ses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.40.74",
    "botocore>=1.40.74",
    "psycopg2>=2.9.11",
]
